sonar.projectKey=xy8000_bike_counter
sonar.organization=xy8000
sonar.sources=backend/src,frontend/src,frontend/public
sonar.exclusions=frontend/public/debug-libs/**,**/node_modules/**,**/target/**,**/coverage/**,**/dist/**
sonar.sourceEncoding=UTF-8