-- Provider-emitted events, scoped per data source.
--
-- A data source has exactly one provider, so data_source_id fully scopes the
-- messages. id is a random application-generated UUID (Uuid::new_v4(), mirroring
-- the other tables) used purely as a stable record identifier. `occurred_at` is
-- generated by the database on insert and is read-only; the caller never
-- supplies it.
CREATE TABLE data_source_provider_messages (
    id UUID PRIMARY KEY,
    data_source_id UUID NOT NULL
        REFERENCES data_sources(id) ON DELETE CASCADE,
    severity TEXT NOT NULL
        CHECK (severity IN ('INFO', 'WARNING', 'ERROR', 'DEBUG', 'TRACE')),
    message TEXT NOT NULL,
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- FK lookups, newest-first per-source listing and cascade cleanup.
CREATE INDEX idx_data_source_provider_messages_data_source_id
    ON data_source_provider_messages (data_source_id);
