use utoipa::OpenApi;

use crate::adapter::driving::bff::{
    __path_get_bff_asset_content, __path_get_bff_data_source_detail, __path_get_bff_data_sources,
    __path_get_bff_global_summary, __path_get_bff_station_detail_graphs,
    __path_get_bff_station_detail_monthly, __path_get_bff_station_detail_overview,
    __path_get_bff_station_detail_page, __path_get_bff_station_overview,
    __path_get_bff_station_overview_stats, __path_get_bff_stations_search,
    __path_get_bff_stations_sidebar, __path_get_bff_stations_sidebar_stats,
    __path_get_bff_stations_summary_graphs, __path_get_bff_stations_summary_monthly,
    __path_get_bff_stations_summary_overview, __path_get_bff_stations_summary_page,
    __path_list_bff_stations, ActionDto, AsOfQueryParams, BffDataSourceDetailDto,
    BffDataSourceImportDto, BffDataSourceListDto, BffDataSourceListItemDto, ChannelRefDto,
    ChannelTotalDto, GlobalSummaryDto, GlobalSummaryQueryParams, HourTotalDto, MetricDto,
    MonthlyTotalsDto, PerChannelSeriesDto, PerStationSeriesDto, PeriodGraphsDto, SidebarShellDto,
    SidebarStationDto, SidebarStationStatsDto, SidebarStatsDto, StationDetailPageDto,
    StationMapDto, StationMapListDto, StationOverviewDto, StationOverviewStatsDto,
    StationSearchDto, StationSummaryDto, StationsSummaryOverviewDto, StationsSummaryPageDto,
    SummaryPeriodGraphsDto, SummaryStationDto, TimeBucketDto, Trend, WeekdayTotalDto,
};
use crate::adapter::driving::rest::dto::{
    ApiRootDto, CancelJobRequestDto, ChannelDto, ChannelListDto, CountingStationDto,
    CountingStationListDto, CountingStationPatchDto, DataSourceDto, DataSourceListDto,
    ErrorResponseDto, HealthComponentDto, HealthDto, JobDto, JobListDto, JobQueryParams,
    JobStatusDto, LinkDto, MeasurementDto, MeasurementListDto, PersistentStateDto,
    PersistentStateEntryDto, PersistentStateValueDto, ProviderMessageDto, ProviderMessageListDto,
    ProviderMessageSeverityDto, RawMeasurementDto,
};
use crate::adapter::driving::rest::handlers::{
    __path_cancel_job, __path_clear_persistent_state, __path_delete_persistent_state_entry,
    __path_get_api_root, __path_get_channel_by_id, __path_get_counting_station_by_id,
    __path_get_data_source_by_id, __path_get_health_live, __path_get_health_ready,
    __path_get_job_by_id, __path_get_measurement_by_id, __path_get_persistent_state,
    __path_list_channels, __path_list_counting_stations, __path_list_data_sources,
    __path_list_jobs, __path_list_measurements, __path_list_measurements_raw,
    __path_list_provider_messages, __path_patch_counting_station, __path_put_persistent_state_entry,
    __path_reset_imported_until,
};

#[derive(OpenApi)]
#[openapi(
    paths(
        list_bff_stations,
        get_bff_data_sources,
        get_bff_data_source_detail,
        get_bff_stations_sidebar,
        get_bff_stations_sidebar_stats,
        get_bff_stations_search,
        get_bff_global_summary,
        get_bff_station_overview,
        get_bff_station_overview_stats,
        get_bff_station_detail_page,
        get_bff_station_detail_overview,
        get_bff_station_detail_graphs,
        get_bff_station_detail_monthly,
        get_bff_stations_summary_page,
        get_bff_stations_summary_overview,
        get_bff_stations_summary_graphs,
        get_bff_stations_summary_monthly,
        get_bff_asset_content,
        get_api_root,
        list_counting_stations,
        get_counting_station_by_id,
        patch_counting_station,
        list_channels,
        get_channel_by_id,
        list_measurements,
        list_measurements_raw,
        get_measurement_by_id,
        list_data_sources,
        get_data_source_by_id,
        reset_imported_until,
        get_persistent_state,
        put_persistent_state_entry,
        delete_persistent_state_entry,
        clear_persistent_state,
        list_provider_messages,
        list_jobs,
        get_job_by_id,
        cancel_job,
        get_health_live,
        get_health_ready,
    ),
    components(
        schemas(
            StationSummaryDto,
            StationMapDto,
            StationMapListDto,
            SidebarStationDto,
            SidebarShellDto,
            SidebarStationStatsDto,
            SidebarStatsDto,
            ActionDto,
            StationSearchDto,
            GlobalSummaryDto,
            GlobalSummaryQueryParams,
            StationOverviewDto,
            StationOverviewStatsDto,
            StationDetailPageDto,
            ChannelRefDto,
            TimeBucketDto,
            WeekdayTotalDto,
            HourTotalDto,
            ChannelTotalDto,
            PerChannelSeriesDto,
            PeriodGraphsDto,
            MonthlyTotalsDto,
            StationsSummaryPageDto,
            StationsSummaryOverviewDto,
            SummaryStationDto,
            SummaryPeriodGraphsDto,
            PerStationSeriesDto,
            MetricDto,
            Trend,
            BffDataSourceListDto,
            BffDataSourceListItemDto,
            BffDataSourceDetailDto,
            BffDataSourceImportDto,
            AsOfQueryParams,
            ApiRootDto,
            CountingStationDto,
            CountingStationListDto,
            CountingStationPatchDto,
            ChannelDto,
            ChannelListDto,
            MeasurementDto,
            MeasurementListDto,
            RawMeasurementDto,
            DataSourceDto,
            DataSourceListDto,
            JobDto,
            JobListDto,
            JobStatusDto,
            JobQueryParams,
            CancelJobRequestDto,
            PersistentStateDto,
            PersistentStateEntryDto,
            PersistentStateValueDto,
            ProviderMessageDto,
            ProviderMessageListDto,
            ProviderMessageSeverityDto,
            LinkDto,
            ErrorResponseDto,
            HealthComponentDto,
            HealthDto,
        )
    ),
    tags(
        (name = "BFF API", description = "Backend-for-Frontend endpoints consumed by the React frontend only"),
        (name = "Root", description = "Root discovery endpoint"),
        (name = "Counting Stations", description = "Operations on bike counting stations"),
        (name = "Channels", description = "Operations on counting station channels"),
        (name = "Measurements", description = "Operations on channel measurements"),
        (name = "Data Sources", description = "External data sources"),
        (name = "Jobs", description = "Generic tracked jobs"),
        (name = "Health", description = "Operational health checks (liveness/readiness)"),
    ),
    info(
        title = "Bike Counter API",
        version = "1.0.0",
        description = "HTTP API of the Bike Counter backend.\n\n- The **BFF API** (`/api/bff`) is consumed by the React frontend only.\n- The **REST API** (`/api/v1`) is the public interface for backend-to-backend integrations.\n- `/health/live` and `/health/ready` are operational checks used by the Docker healthcheck.\n\nCacheable BFF JSON responses carry a `Cache-Control` freshness policy and a strong `ETag` (a SHA-256 of the body) and honor `If-None-Match` with `304 Not Modified`."
    )
)]
pub struct ApiDoc;
