//! Driven (outbound) port: persistence for provider messages, scoped per data
//! source. Implemented by `PostgresProviderMessageRepository`; consumed by the
//! provider-message service and by the scoped
//! [`ProviderMessageSink`](super::provider_port::ProviderMessageSink) handle
//! (built via
//! [`ProviderMessageSinkFactory`](super::provider_port::ProviderMessageSinkFactory)).
//!
//! The [`ProviderMessage`] model and [`ProviderMessageSeverity`] live in the
//! sibling `provider_message.rs`.

use chrono::{DateTime, Utc};

use super::data_source::value_objects::Id;
use super::provider_message::ProviderMessage;
use super::provider_message::ProviderMessageSeverity;
use crate::core::domain::error::DomainError;

/// Persistence port for provider messages, scoped per data source.
pub trait ProviderMessageStore: Send + Sync {
    /// Persists a message. `occurred_at` is generated by the database and
    /// returned as part of [`ProviderMessage`] on read-back.
    fn record(
        &self,
        data_source_id: Id,
        severity: ProviderMessageSeverity,
        message: &str,
    ) -> Result<(), DomainError>;

    /// Returns all messages for a data source, ordered newest first.
    fn find_by_data_source(&self, data_source_id: Id) -> Result<Vec<ProviderMessage>, DomainError>;

    /// Counts the persisted messages of one severity recorded at or after
    /// `since`. The data-sources UI uses this to show how many warnings/errors
    /// the last import produced (a run is the only writer of its source at any
    /// moment). The default returns 0 so in-memory doubles that never exercise
    /// this need no change; the Postgres adapter pushes the filter into SQL.
    fn count_since(
        &self,
        _data_source_id: Id,
        _severity: ProviderMessageSeverity,
        _since: DateTime<Utc>,
    ) -> Result<i64, DomainError> {
        Ok(0)
    }
}
