//! Model: provider-emitted messages, scoped per data source.
//!
//! Providers surface non-fatal conditions (and lifecycle tracing) by emitting
//! short messages through a scoped [`ProviderMessageSink`] instead of aborting
//! the whole update job with a major failure. The messages are persisted
//! read-only through the [`ProviderMessageStore`] port
//! (`provider_message_port.rs`) and exposed by the core.

use std::fmt;
use std::str::FromStr;

use chrono::{DateTime, Utc};

use super::data_source::value_objects::Id;
use crate::core::domain::error::DomainError;

/// Severity of a provider message. The wire and database representation is the
/// upper-case string (`INFO`, `WARNING`, `ERROR`, `DEBUG`, `TRACE`).
///
/// Ordering is from least to most severe: `TRACE < DEBUG < INFO < WARNING <
/// ERROR`. A message is persisted when its severity is **at or above** the
/// configured provider log level.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ProviderMessageSeverity {
    Info,
    Warning,
    Error,
    Debug,
    Trace,
}

impl ProviderMessageSeverity {
    /// The upper-case wire/database representation of this severity.
    pub fn as_str(&self) -> &'static str {
        match self {
            ProviderMessageSeverity::Info => "INFO",
            ProviderMessageSeverity::Warning => "WARNING",
            ProviderMessageSeverity::Error => "ERROR",
            ProviderMessageSeverity::Debug => "DEBUG",
            ProviderMessageSeverity::Trace => "TRACE",
        }
    }

    /// The severity rank from least (0, `TRACE`) to most severe (4, `ERROR`).
    pub fn rank(&self) -> u8 {
        match self {
            ProviderMessageSeverity::Trace => 0,
            ProviderMessageSeverity::Debug => 1,
            ProviderMessageSeverity::Info => 2,
            ProviderMessageSeverity::Warning => 3,
            ProviderMessageSeverity::Error => 4,
        }
    }

    /// Whether this severity is at least as severe as `threshold` (i.e. should
    /// be kept when `threshold` is the configured log level).
    pub fn at_or_above(&self, threshold: ProviderMessageSeverity) -> bool {
        self.rank() >= threshold.rank()
    }
}

impl fmt::Display for ProviderMessageSeverity {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl FromStr for ProviderMessageSeverity {
    type Err = DomainError;

    fn from_str(raw: &str) -> Result<Self, Self::Err> {
        match raw {
            "INFO" => Ok(ProviderMessageSeverity::Info),
            "WARNING" => Ok(ProviderMessageSeverity::Warning),
            "ERROR" => Ok(ProviderMessageSeverity::Error),
            "DEBUG" => Ok(ProviderMessageSeverity::Debug),
            "TRACE" => Ok(ProviderMessageSeverity::Trace),
            _ => Err(DomainError::InvalidQuery(format!(
                "unknown provider message severity: {raw}"
            ))),
        }
    }
}

/// A single provider-emitted event for a data source.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProviderMessage {
    pub id: uuid::Uuid,
    pub data_source_id: Id,
    pub severity: ProviderMessageSeverity,
    /// Human-readable one-line event text.
    pub message: String,
    /// Auto-generated by the database on insert; read-only.
    pub occurred_at: DateTime<Utc>,
}

#[cfg(test)]
mod tests {
    use std::str::FromStr;

    use super::ProviderMessageSeverity;

    #[test]
    fn severity_round_trips_through_upper_case_strings() {
        for (raw, severity) in [
            ("INFO", ProviderMessageSeverity::Info),
            ("WARNING", ProviderMessageSeverity::Warning),
            ("ERROR", ProviderMessageSeverity::Error),
            ("DEBUG", ProviderMessageSeverity::Debug),
            ("TRACE", ProviderMessageSeverity::Trace),
        ] {
            assert_eq!(severity.as_str(), raw);
            assert_eq!(ProviderMessageSeverity::from_str(raw).unwrap(), severity);
            assert_eq!(severity.to_string(), raw);
        }
    }

    #[test]
    fn rejects_unknown_severity_strings() {
        assert!(ProviderMessageSeverity::from_str("NOTICE").is_err());
        assert!(ProviderMessageSeverity::from_str("").is_err());
    }

    #[test]
    fn at_or_above_orders_severities() {
        // Least -> most severe: TRACE < DEBUG < INFO < WARNING < ERROR.
        assert!(ProviderMessageSeverity::Debug.at_or_above(ProviderMessageSeverity::Trace));
        assert!(!ProviderMessageSeverity::Debug.at_or_above(ProviderMessageSeverity::Info));
        assert!(!ProviderMessageSeverity::Debug.at_or_above(ProviderMessageSeverity::Warning));

        // The default WARNING level keeps WARNING and ERROR, drops below.
        assert!(ProviderMessageSeverity::Warning.at_or_above(ProviderMessageSeverity::Warning));
        assert!(ProviderMessageSeverity::Error.at_or_above(ProviderMessageSeverity::Warning));
        assert!(!ProviderMessageSeverity::Info.at_or_above(ProviderMessageSeverity::Warning));
        assert!(!ProviderMessageSeverity::Debug.at_or_above(ProviderMessageSeverity::Warning));
        assert!(!ProviderMessageSeverity::Trace.at_or_above(ProviderMessageSeverity::Warning));

        // TRACE is the minimum level: everything is at or above it.
        assert!(ProviderMessageSeverity::Trace.at_or_above(ProviderMessageSeverity::Trace));
        assert!(ProviderMessageSeverity::Debug.at_or_above(ProviderMessageSeverity::Trace));

        // ERROR is the maximum level: at or above every threshold, and nothing
        // is above it.
        assert!(ProviderMessageSeverity::Error.at_or_above(ProviderMessageSeverity::Trace));
        assert!(ProviderMessageSeverity::Error.at_or_above(ProviderMessageSeverity::Error));
        assert!(!ProviderMessageSeverity::Warning.at_or_above(ProviderMessageSeverity::Error));
    }
}
