#!/usr/bin/env bash
#
# One-time build of the self-hosted vector basemap for the Martin tile server.
#
# Builds an OpenMapTiles-schema .pmtiles from a Geofabrik extract using
# Planetiler (https://github.com/onthegomap/planetiler), writing it to
# tiles/basemap.pmtiles — the file the `martin` docker service serves (see
# tiles/README.md for alternatives, e.g. dropping in a pre-built .pmtiles).
#
# This is a manual, one-off data-preparation step, NOT part of any Make gate:
# the map markers/popups render without the basemap, so CI stays green even
# before this is run.
#
# Memory: the script uses Planetiler's low-RAM profile by default
# (`--storage=mmap --nodemap-type=sparse`), which keeps the working set in
# memory-mapped temp files instead of the JVM heap. A ~8-10 GB heap is enough
# for the `germany` extract on a 14 GB machine (stop the docker stack first so
# the build has the RAM: `docker compose down`). Override with JAVA_MEM (e.g.
# `JAVA_MEM="-Xmx16g"`), STORAGE (`ram`) and NODEMAP_TYPE (`array`) on a big
# machine for a faster build.
#
# Prerequisites:
#   - Java 21+  (java -version)
#   - ~10 GB free RAM for `germany` (with the low-RAM profile; a smaller region
#     needs less). The old `-Xmx16g` default crashed on 14 GB machines.
#   - Network access to Geofabrik (the extract is downloaded on first run).
#
# Usage: ./scripts/build_tiles.sh [region]
#   region   Geofabrik region id (default: germany). Examples: germany,
#            nordrhein-westfalen, hamburg, monaco (tiny, quick smoke test).
set -euo pipefail

REGION="${1:-germany}"
PLANETILER_JAR="planetiler.jar"
OUTPUT="tiles/basemap.pmtiles"
# NOTE: valid Planetiler nodemap types are [noop, sortedtable, sparsearray,
# array]; `sparse`/`chunkedtable` crash with "Unexpected long long map type".
# `sortedtable` is the disk-backed, low-RAM choice.
JAVA_MEM="${JAVA_MEM:--Xmx4g}"
NODEMAP_TYPE="${NODEMAP_TYPE:-sortedtable}"
STORAGE="${STORAGE:-mmap}"

# Resolve the repo root from this script's location, so the script works from
# any working directory.
WORKDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

mkdir -p "$WORKDIR/tiles"

if [ ! -f "$WORKDIR/$PLANETILER_JAR" ]; then
  echo "Downloading Planetiler (latest release) ..."
  curl -fL -o "$WORKDIR/$PLANETILER_JAR" \
    "https://github.com/onthegomap/planetiler/releases/latest/download/planetiler.jar"
fi

echo "Building $OUTPUT for region '$REGION' (JAVA_MEM=$JAVA_MEM, storage=$STORAGE, nodemap=$NODEMAP_TYPE) ..."
cd "$WORKDIR"
# `--download` fetches the extract and Planetiler's auxiliary input files (lake
# centerlines, water polygons, Natural Earth) on first run.
java "$JAVA_MEM" -jar "$PLANETILER_JAR" \
  --area="$REGION" \
  --download \
  --output="$OUTPUT" \
  --nodemap-type="$NODEMAP_TYPE" \
  --storage="$STORAGE"

echo "Done. Restart martin to pick up the new basemap:"
echo "  docker compose up -d --force-recreate martin"
echo "Verify (Germany detail tile through the BFF proxy, extension-less URL):"
echo "  curl -s -o /dev/null -w '%{http_code} %{content_type}\\n' http://localhost:8081/api/map/basemap/13/4269/2707"
echo "The zoomed-out world view is served separately by tiles/world.mbtiles"
echo "(Natural Earth, zoom 0-5; generated by frontend/scripts/build-world-tiles.mjs)."
