#!/usr/bin/env bash
# Generates frontend/e2e/e2e-seed.sql — a small, committed SQL fixture for the
# Playwright e2e suite (make test-playwright).
#
# The fixture is derived from the running stack's database (docker compose):
#   * the full schema + refinery migration history, so `create_pool` skips the
#     migrations,
#   * the three data_sources (deterministic UUIDv5 ids matching the config names),
#   * every counting station + channel (image links stripped so the builtin
#     fallback bike icon is used, since the e2e MinIO bucket only holds builtins),
#   * synthesized recent measurements for the alphabetically-first stations of
#     each city — the BFF returns stations name-ordered, so the first map marker /
#     search hit per city always has data; timestamps are generated relative to
#     load time (now() - interval ...) so the fixture never ages,
#   * pre-finished jobs for the three schedulers, so the backend skips the
#     startup import, the asset cleanup and the tile rebuild.
#
# The e2e stack loads the fixture on a fresh DB volume (docker-entrypoint-initdb.d
# via frontend/e2e/docker-compose.e2e.yml), making the run fully offline w.r.t.
# the providers.
#
# Requirements: the stack must be running (`docker compose up -d`), because the
# dump is taken through the running `db` service.
set -euo pipefail

SCRIPT_DIR="$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")"
PROJECT_ROOT="$(dirname "${SCRIPT_DIR}")"
OUT="${PROJECT_ROOT}/frontend/e2e/e2e-seed.sql"

# Runs inside the running `db` container against the application database.
PSQL=(docker compose exec -T db psql -U postgres -d bike_counter)
PGDUMP=(docker compose exec -T db pg_dump -U postgres -d bike_counter --no-owner --no-privileges)

{
  echo "-- E2E fixture seed (generated by scripts/dump-e2e-fixture.sh)."
  echo "-- Loaded by the Playwright stack on a fresh DB volume; see"
  echo "-- scripts/e2e-playwright.sh + frontend/e2e/docker-compose.e2e.yml."

  echo
  echo "-- Schema (tables, indexes, functions, triggers, refinery history table)."
  "${PGDUMP[@]}" --schema-only

  echo
  echo "-- Refinery migration history (all migrations already applied, so"
  echo "-- create_pool prints 'not necessary' and skips)."
  "${PGDUMP[@]}" --data-only --table=refinery_schema_history

  echo
  echo "-- Data sources (ids are deterministic UUIDv5 of the config names)."
  "${PGDUMP[@]}" --data-only --table=data_sources

  echo
  echo "-- Assets (metadata only; provider objects are not synced into the e2e"
  echo "-- MinIO bucket, so the stations are unlinked below). Dumped before the"
  echo "-- counting stations so their image_asset_id FK resolves."
  "${PGDUMP[@]}" --data-only --table=assets

  echo
  echo "-- Counting stations and channels (all)."
  "${PGDUMP[@]}" --data-only --table=counting_stations
  "${PGDUMP[@]}" --data-only --table=channels

  echo
  echo "-- Persistent state + provider messages (usually empty)."
  echo "-- (schema-only, plus any rows already present)."
  "${PGDUMP[@]}" --data-only --table=data_source_persistent_state
  "${PGDUMP[@]}" --data-only --table=data_source_provider_messages

  echo
  echo "-- Restore the default search_path (the dump above set it to ''), so the"
  echo "-- unqualified statements below resolve the tables."
  echo "SET search_path = public;"
  echo
  echo "-- Unlink provider images so the builtin fallback bike icon is used."
  echo "UPDATE counting_stations SET image_asset_id = NULL, image_sha256 = NULL;"

  cat <<'SQL'

-- Synthesized recent measurements for the alphabetically-first stations of each
-- city (real station/channel structure from the DB; generated values keep the
-- fixture small and the timestamps relative to load time). The resolutions
-- mirror the real sources: Münster 900s, Bonn 3600s, Hamburg 300s.
INSERT INTO measurements (id, value, channel_id, timestamp, resolution_seconds, interval_end)
SELECT gen_random_uuid(),
       (30 + (60 * abs(sin(extract(epoch FROM ts) / 3600.0)))::int
            + ((extract(dow FROM ts))::int % 3) * 20)::bigint,
       c.id,
       ts,
       CASE d.name WHEN 'Münster' THEN 900 WHEN 'Bonn' THEN 3600 ELSE 300 END,
       NULL
FROM channels c
JOIN counting_stations s ON s.id = c.counting_station_id
JOIN data_sources d ON d.id = s.data_source_id
CROSS JOIN LATERAL generate_series(
    now() - (CASE d.name
               WHEN 'Münster' THEN interval '45 days'
               WHEN 'Bonn'    THEN interval '60 days'
               ELSE                interval '14 days'
             END),
    now(),
    make_interval(secs => CASE d.name WHEN 'Münster' THEN 900 WHEN 'Bonn' THEN 3600 ELSE 300 END)
) AS ts
WHERE (d.name = 'Münster' AND s.name IN ('Bismarckallee', 'Bohlweg', 'Coesfelder Kreuz'))
   OR (d.name = 'Bonn'    AND s.name IN ('BN - Bröltalbahnweg', 'BN - Brühler Straße', 'BN - Estermannufer'))
   OR (d.name = 'Hamburg' AND s.name IN ('MQ1.2', 'MQ1.3', 'MQ10.1+10.2'));

-- Pre-finished jobs: the schedulers skip their startup run (never overdue — the
-- data_source_update finished_at is in the future so the cron-based overdue test
-- can never fire) and the stack boots without importing from the providers.
INSERT INTO jobs (id, name, job_type, status, started_at, finished_at, failure_message, metadata, lifetime_until, max_lifetime_exceeded, created_at)
VALUES
  (gen_random_uuid(), 'Data source update', 'data_source_update', 'FINISHED',
   now() - interval '1 minute', now() + interval '1 hour', NULL, '{}'::jsonb,
   now() + interval '2 hours', FALSE, now() - interval '1 minute'),
  (gen_random_uuid(), 'asset cleanup', 'asset_cleanup', 'FINISHED',
   now() - interval '1 hour', now() - interval '1 hour', NULL, '{}'::jsonb,
   now() + interval '1 hour', FALSE, now() - interval '1 hour'),
  (gen_random_uuid(), 'tiles update', 'tiles_update', 'FINISHED',
   now() - interval '2 hours', now() - interval '2 hours', NULL, '{}'::jsonb,
   now() + interval '1 hour', FALSE, now() - interval '2 hours');

-- The rolling data is generated up to now(); anchor the imported_until cursor so
-- a later manual import resumes from the fixture's most recent data.
UPDATE data_sources SET imported_until = now() WHERE imported_until IS NOT NULL;
SQL
} > "${OUT}"

echo "Wrote ${OUT}"
echo "Size: $(du -h "${OUT}" | cut -f1)"
