//! Driven (outbound) port: persistence for provider messages, scoped per data
//! source. Implemented by `PostgresProviderMessageRepository`; consumed by the
//! provider-message service and by the scoped
//! [`ProviderMessageSink`](super::provider_port::ProviderMessageSink) handle
//! (built via
//! [`ProviderMessageSinkFactory`](super::provider_port::ProviderMessageSinkFactory)).
//!
//! The [`ProviderMessage`] model and [`ProviderMessageSeverity`] live in the
//! sibling `provider_message.rs`.

use super::data_source::value_objects::Id;
use super::provider_message::ProviderMessage;
use super::provider_message::ProviderMessageSeverity;
use crate::core::domain::error::DomainError;

/// Persistence port for provider messages, scoped per data source.
pub trait ProviderMessageStore: Send + Sync {
    /// Persists a message. `occurred_at` is generated by the database and
    /// returned as part of [`ProviderMessage`] on read-back.
    fn record(
        &self,
        data_source_id: Id,
        severity: ProviderMessageSeverity,
        message: &str,
    ) -> Result<(), DomainError>;

    /// Returns all messages for a data source, ordered newest first.
    fn find_by_data_source(&self, data_source_id: Id) -> Result<Vec<ProviderMessage>, DomainError>;
}
